filebeat.prospectors:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: http://172.17.0.1:5601
  username: elastic
  password: pass

output.elasticsearch:
  hosts: ["http://172.17.0.1:9200"]
  username: elastic
  password: pass
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
