---
## App Search core configuration
## https://swiftype.com/documentation/app-search/self-managed/configuration
#

# IP address App Search listens on
app_search.listen_host: 0.0.0.0

# URL at which users reach App Search
app_search.external_url: http://localhost:3002

# Elasticsearch URL and credentials
elasticsearch.host: http://elasticsearch:9200
elasticsearch.username: elastic
elasticsearch.password: changeme

# Allow App Search to modify Elasticsearch settings. Used to enable auto-creation of Elasticsearch indexes.
allow_es_settings_modification: true
